### PR TITLE
fixed minor typo

### PR DESCRIPTION
**Pull request by wle8300**
sup! thx for making this module!

### CODE REVIEW

**Comment by robinweser** [comment]
Thanks @williamle8300 :)

I will be adding plenty new components soon. Including TabView, ScrollView and other stuff :P

**Comment by wle8300** [comment]
Np. Sick! Are these abstractions coming from React-Native land?

**Comment by robinweser** [comment]
Well yeah, the concept is the same and I think they originally come from UIKit (iOS) and I think they're awesome as base components for layouting almost any possible problem out there

**Comment by wle8300** [comment]
yea man. I love the clean interface you got for this module. keep up the great work!

cheers.

**Pull request merged**
